### ISSUE TITLE
Provide build and run instructions

### ISSUE THREAD

**Issue by chris-aeviator** [sschuberth/stan#12]
It is unclear howto build and run this project.

When running `gradle run` I will get an error saying that no file has been specified, when appending the file path to the command I cannot get it running either. Please also show how to display the help messages provided in code

**Comment by sschuberth** [comment]
@chris-aeviator can you please check whether https://github.com/sschuberth/stan/pull/14 is good enough for you?

**Comment by sschuberth** [comment]
Feel free to reopen if there's still some unclarity.
