### ISSUE TITLE
Error parsing booking summary with Postbank PDF from 2020

### ISSUE THREAD

**Issue by chris-aeviator** [sschuberth/stan#13]
When using Stan with an up2date PDF report from Postbank (Geschaeftskonto), an not further specified error `Error parsing booking summary` is output. No further processing is done

**Comment by sschuberth** [comment]
Probably a statement for a "Geschaeftskonto" uses a slightly different wording / layout than one for a "Privatkonto". I've added some more output to the exception message. Can you please give it a try and report back?

**Comment by chris-aeviator** [comment]
I remember downloading a binary from releases section, is this gone?

**Comment by sschuberth** [comment]
No, there never was a binary release yet.

**Comment by chris-aeviator** [comment]
I will try to re-build later today, I can find `stan` in my history only beeing run as executable

**Comment by sschuberth** [comment]
You probably followed the newly added [instructions](https://github.com/sschuberth/stan#how-to-run-the-command-line-tool) and did build the executable script yourself.

**Comment by chris-aeviator** [comment]
It was me asking for them :-)

I will check for this

**Comment by sschuberth** [comment]
I know, that's why I assumed you also did actually try them out 😉

**Comment by sschuberth** [comment]
I've now also added support for passing (debug) options to parsers. You can use

    ./gradlew :cli:run --args="PB.pdf -P postbankpdf=text.output=true -f excel"

to let the parser output the plain text version of the PDF before the actual parsing starts. If you can anonymize that plain text file (by only replacing numbers with numbers and letters with letters, without changing the format in any way) and attach it here, I could debug your issue.

**Comment by sschuberth** [comment]
Closing this due to a lack of feedback. Feel free to reopen @chris-aeviator if you have any more information.

**Comment by chris-aeviator** [comment]
sorry for the late reply - I found that https://github.com/marvinbernhardt/postbank2csv parses a whole year of Poba Businessaccount pdfs within few seconds so I did not further look into this
